name = "Axiom"
license = "CC-BY-SA-4.0"
licenselink = "https://github.com/marketempower/axiom/blob/master/LICENSE"
homepage = "https://www.axiomtheme.com/"
description = "Axiom is a powerful, high performance, modular Hugo theme, designed to make the readers of your content and the search engines happy."
tags = ["seo", "organic-search", "structured-data", "cdn", "cloudinary", "netlify", "jamstack", "responsive-images", "pagespeed-95", "sharing", "atom-feed", "npm-scripts", "custom-css", "custom-js", "blog", "chroma", "modular", "fast", "responsive", "tailwindcss", "alpinejs", "seo"]
features = ["seo", "organic-search", "structured-data", "cdn", "cloudinary", "netlify", "jamstack", "responsive-images", "pagespeed-95", "sharing", "atom-feed", "npm-scripts", "custom-css", "custom-js", "blog", "chroma", "modular", "fast", "responsive", "tailwindcss", "alpinejs", "seo"]
min_version = "0.70.0"

[author]
name = "Jhaura Wachsman"
homepage = "https://www.jhaurawachsman.com/"
